source "https://rubygems.org"
ruby '2.2.1'
gem 'sinatra', '1.4.6'
gem 'puma', '2.11.1'
gem 'bundler-audit', '0.3.1'
gem 'sinatra-activerecord'
gem 'mysql'
gem 'activerecord', '~> 3.0'
gem 'will_paginate'
gem 'rerun'
